apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ args.cluster.name }}
  namespace: {{ args.namespace }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ args.cluster.kafka.version }}
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ args.cluster.kafka.replicas }}
      transaction.state.log.replication.factor: {{ args.cluster.kafka.replicas }}
      transaction.state.log.min.isr: {{ args.cluster.kafka.min_isr }}
      default.replication.factor: {{ args.cluster.kafka.replicas }}
      min.insync.replicas: {{ args.cluster.kafka.min_isr }}
  entityOperator:
    topicOperator: {}
    userOperator: {}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: {{ args.cluster.name }}
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ args.cluster.kafka.storage_size }}
        deleteClaim: false
        kraftMetadata: shared
