apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: liquid-snake
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 1
  config:
    retention.ms: 86400000
    min.insync.replicas: 1
